services:
  api:
    build:
      context: .
    command: yarn docker:start
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://192.168.18.101:27017/express-rest-es2017-boilerplate
